### PR TITLE
Fixing test

### PR DESCRIPTION
**Pull request by berdon**

### CODE REVIEW

**Review by jpeters5392 — APPROVED** [review]

**Review by mahmuto — APPROVED** [review]

**Comment by turowicz** [comment]
@berdon is this project still alive?

I'm looking to use redis but I'm on orleans 3.5.x

**Comment by berdon** [comment]
It is being used, actively, by a company's product. I'm no longer on that team though. :)

**Comment by turowicz** [comment]
@berdon would you say its production ready?

**Comment by turowicz** [comment]
@berdon not many recent commits...

**Comment by berdon** [comment]
@turowicz It's currently being used in a production product fielding hundreds of customers. ¯\\\_(ツ)\_/¯ YMMV but it's pretty simple and hasn't had many issues over it's life.

**Pull request merged**
